### ISSUE TITLE
Status LEDs

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#12]
Where should Status LEDs be accessible?
How much are they needed?

They (Lime Microsystems) suggest we use:
4x LED GRN/RED DIFF 3MM ROUND T/H  (Digi-Key    4301F1/5-ND)
2x LED_STANDOFF_H-201C                     (Digi-Key    492-1790-ND)
the board was designed for (BOM)

![2016-10-03 21_48_00-h-20_c-_ _ bivar inc - h-20xc-x pdf google chrome](https://cloud.githubusercontent.com/assets/1379063/19051577/bfafdfa4-89b3-11e6-9d81-c0c09fcdd502.png)

![2016-10-03 21_50_28-limesdr_1v2_schematic pdf - exportschematic - sumatrapdf](https://cloud.githubusercontent.com/assets/1379063/19051559/b7e67a3a-89b3-11e6-8310-7e6ccde57af5.png)

![2016-10-03 21_30_57-program manager](https://cloud.githubusercontent.com/assets/1379063/19050884/dd0efb50-89b0-11e6-8e12-efb39cbf6c26.png)

![2016-10-03 21_31_09-freecad](https://cloud.githubusercontent.com/assets/1379063/19050883/dd0e8b02-89b0-11e6-94f3-0470a26b4164.png)

**Comment by zigastegu** [comment]
Just standoff: http://eu.mouser.com/ProductDetail/Bivar/H-201C/?qs=sGAEpiMZZMtU66%252bVMtdfbiIxtAK9LgjB
Assortment on Mouser of assembled leds: http://eu.mouser.com/Optoelectronics/LED-Indication/LED-Circuit-Board-Indicators/_/N-b1d1l?P=1yzmx6iZ1z0wugs&Ns=Pricing%7c0

http://vcclite.com/product/cbi-2pos-bi-level-led-4/

Dialight:
http://www.farnell.com/datasheets/12842.pdf
http://www.ebay.com/itm/181623620539

**Comment by luftek** [comment]
http://vcclite.com/product/cbi-2pos-bi-level-led-4/

**Comment by zigastegu** [comment]
CONSIDERING LIGHT PIPES
light fiber + 4 small holes on rear and front panel (1.2 mm)

Have not find anything DIY yet.
Concern is mounting on LEDs in semi permanent fashion.

Light fiber in diameter of 1mm (blue outline) would cover both dies on this small 0603 leds
![image](https://cloud.githubusercontent.com/assets/1379063/19985928/162bb2e4-a215-11e6-85b7-64c8a7884df0.png)

I can currently only try 0.35 mm wide light fiber used in:
![image](https://cloud.githubusercontent.com/assets/1379063/19986050/82b15298-a215-11e6-878c-e75207de43f0.png)

**Comment by zigastegu** [comment]
Commit: dc9700f for design files 1v0 predicts already made holes for LEDs
