### ISSUE TITLE
Enclosure of lower height/profile for 4 conn version

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#13]
Nice! I bought one. Do you have any plans for releasing another case with lower height? Thanks. - freebil

**Comment by luftek** [comment]
maybe 100*71*25mm http://www.everestcase.com/upload/2014071515071066.pdf5 (datasheet is not complete)
http://www.everestcase.com/en/productsd.php?pid=11662 which can be probably same as http://www.ebay.com/itm//2016284554915

**Comment by zigastegu** [comment]
### Candidates according to approx. size filter

60 < width <80
20 < height < 30
legth = 100

http://www.everestcase.com/en/productsd.php?pid=1166 [W71×H24.8×L100 mm]
http://www.everestcase.com/en/productsd.php?pid=877   [W69×H24×L100 mm]
http://www.everestcase.com/en/productsd.php?pid=802   [W66×H27×L100 mm]
http://www.everestcase.com/en/productsd.php?pid=901   [W74×H22×L100 mm]

**Comment by zigastegu** [comment]
I found datasheet, with most dimension marked, on Taobao (a lot of edited ones).
W71xH25xL100
This seems to be closes to original:

![image](https://cloud.githubusercontent.com/assets/1379063/20439233/f4168a06-adba-11e6-92c2-64010aa73dda.png)

https://world.taobao.com/item/523348265980.htm#detail 
https://img.alicdn.com/imgextra/i1/116848420/TB2VrbAbXXXXXasXpXXXXXXXXXX_!!116848420.jpg

**Comment by zigastegu** [comment]
Sample of 
Rear_panel_71x25 in production with some other boards

![image](https://cloud.githubusercontent.com/assets/1379063/20443498/553e5f86-adcd-11e6-85f6-36d2ba994d95.png)
![image](https://cloud.githubusercontent.com/assets/1379063/20443509/5f0d3492-adcd-11e6-8e37-ce0d1d3bee3b.png)

**Comment by zigastegu** [comment]
shipped from Fab

**Comment by zigastegu** [comment]
Received the sample. Unfortunatelly, did not receive enclosure yet
![img_20161210_174753](https://cloud.githubusercontent.com/assets/1379063/21074782/ae26fdac-bf01-11e6-81e7-f0b72175a1a2.jpg)

I have too much of this back plates now. :/ :)

**Comment by zigastegu** [comment]
- bit crammed, where is place for LEDs?
- 4 mount holes need more clearance, so panel can be alligned easier
![15784738_10211399928379658_797933273_o](https://cloud.githubusercontent.com/assets/1379063/21542278/ff7cfb9c-cdbc-11e6-83bf-b3abad15fcb7.jpg)

should i then divide into 2 panels, one for 4 front connectors and one for 10 front connectors?
should i pursue whole enclosure kit assembly with cutouts made in aluminum? MOQ 100pcs :/

**Comment by zigastegu** [comment]
This development was discontinued. 🤔🤦
