### ISSUE TITLE
Naming order RX, front panel

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#2]
"The only thing I can see that I would have liked to be different was the order of the RX connectors.  On the LimeSDR board they are L, H, W and the panel they are marked L,W,H.  Not a big problem but maybe nice if they were in the same order."

John g0orx/n6lyt

**Comment by m3us** [comment]
As long as it is labelled ,I don't think it is a big issue.

**Comment by zigastegu** [comment]
They seem to be named W, L, H ?
![2016-09-11 13_17_06-limesdr_1v2_pcb3d pdf - adobe reader](https://cloud.githubusercontent.com/assets/1379063/18416896/00b00ba8-7822-11e6-9a0f-758046940136.png)
