### ISSUE TITLE
LimeSDR Mini Edition

### ISSUE THREAD

**Issue by Manouchehri** [luftek/LimeSDR-USB#20]
Bit early, but thought I'd comment that it'd be awesome to see a similar (and smaller) enclosure for the LimeSDR Mini when it comes out.

**Comment by zigastegu** [comment]
https://github.com/myriadrf/LimeSDR-Mini design files are available
Forked: https://github.com/luftek/LimeSDR-Mini

**Comment by Manouchehri** [comment]
Nice, thanks!

**Comment by zigastegu** [comment]
I can just add that plastic enclosures for Mini Editions exist and seems to do a decent job protecting the board.
**I really like:**
Yet another LimeSDR Mini Case by ornotermes
https://www.thingiverse.com/thing:3120637

According to licence I could also made it available though **eBay store:**
https://www.ebay.com/itm/123395291206
