### ISSUE TITLE
LED improvements

### ISSUE THREAD

**Issue by ynezz** [luftek/LimeSDR-USB#21]
Hi,

thanks a lot for a great case and a this project! Just a small nitpicks:

1. I had to drill bigger holes(+1mm in diameter) for the 4 LEDs, otherwise I wouldn't be able to put it all together with the screws. Bottom of the LEDs are wider by about 1mm in diameter so the 3mm hole isn't big enough so the front panel doesn't align with the aluminium case.

2. I miss the description of the LEDs on the panel. Maybe you can add the some info about the LEDs in the free space above USB and PWR connectors? Or just move the clock IN/OUT connectors more to the left (above USB/PWR connectors) and add description of the LEDs above the LEDs?

**Comment by zigastegu** [comment]
Thank you for taking the time to comment here!

1. Leds don't fit in plastic holders without modification. Please check instructions for assembly? Maybe something is not well described. I could not source "original" ones. No need to drill holes on PCB/rear panel.

2. Hm... Yes I guess something could be done for predefined ones

Any visual explanation for both comments would be very helpful to me.

**Comment by ynezz** [comment]
>  Please check instructions for assembly?

I've found this GitHub repository after I've finished the assembly, in the guide found in this reposiotry it's pretty clear, that you've modified LEDs so they fit in the holes. I've simply completed the assembly from the photos on your eBay listing as I couldn't find any mention about this assembly instructions, maybe I've just missed it :-)

>  Maybe something is not well described

It's OK, maybe just put small paper with URL to the assembly instructions to the package?

> Yes I guess something could be done for predefined ones

Just some description of the LEDs, so it's clear which one is `LED1`, `LED4`, `FX3/USB` and `Power`. Currently there's no text describing the purpose of the LEDs and one has to [open image with description](https://wiki.myriadrf.org/images/c/cb/LimeSDR-USB-LEDs.jpg) to find out which one is `LED1` for example.

I understand, that `LED1` and `LED4` are user configurable LEDs, but this could be fixed with either custom front panel or custom sticker once needed.

**Comment by zigastegu** [comment]
Assembly instructions: [Instructions.md ](https://github.com/luftek/LimeSDR-USB/blob/master/hardware/enclosure/1v0_76x35_kpl/Instructions.md)
Link to Github on listing for panel not directly as in listing for KIT.

**Comment by zigastegu** [comment]
Rear panel view:
R top:
- VCC3P3, green means power is applied and rail 3v3 works
- red is NC (not connected)

R bottom:
- FX3, green idle
- FX3, red means USB data flow 

L top:
- /

L bottom:
- / (when idle - toggle between green and red, streaming - only green toggles, red turned off)

Observations:
When streaming R bottom is red and L bottom is flashing just green
