### ISSUE TITLE
Type suggestion for 12x SMA U.FL pigtails

### ISSUE THREAD

**Issue by aentinger** [luftek/LimeSDR-USB#24]
Hi @zigastegu :wave:

Great kit, I'm currently working on assembling it. However, I need a bit of help with those **12x SMA U.FL pigtails (5cm/2inch in this manual)** connectors. I've looked around a bit on various pages (Farnell Element 14, Mouser) and have not been able to find such short cables. As I'd like to avoid a bad purchase would you please be so kind as to share the type identification of the pigtails used in your assembly?

All the best, Alex

**Comment by zigastegu** [comment]
Hi. In eBay listing I suggest this ones:
https://www.ebay.com/itm/171598054838?var=470590537181

**Comment by aentinger** [comment]
Thank you :rocket:
