### ISSUE TITLE
Questions regarding BOM for new enclosure

### ISSUE THREAD

**Issue by m3us** [luftek/LimeSDR-USB#5]
I just went through the BOM you put up and purchased most of the items except the set of 8*m2.5 screws 

![image](https://cloud.githubusercontent.com/assets/6883277/18088963/9653bd56-6ece-11e6-9982-26c27a06aac8.png)

Don't cases come with those screws already
![image](https://cloud.githubusercontent.com/assets/6883277/18088978/b130e194-6ece-11e6-982d-7cbd37dd5289.png)

Also what do the rubber pads do?

**Comment by zigastegu** [comment]
Correct, phillips head screws are included with enclosure.
Put rubber pads on bottom so enclosure won't slide on your table. :)
