### ISSUE TITLE
Heat dissipation 

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#7]
Things could get hot, do we need to add cooling holes on the panels?
Maybe transfer heat to the enclosure?

**Comment by m3us** [comment]
LimeSDR draws around 3W to 4W MAX.But I guess vents would'nt hurt.
The aluminum case by Lime systems has vent slots

![image](https://cloud.githubusercontent.com/assets/6883277/18418305/60c8aa4a-7854-11e6-9d57-12e4e1d8366a.png)

**Comment by zigastegu** [comment]
thank you @m3us !
added holes on Rear panel
