### ISSUE TITLE
Text on which layer? Silkscreen or Soldermask

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#8]
I am not sure which is best option for text.
Silkscreen could have manufacturing restrictions while soldermask is usually accurate.

I have this process capability card in my hand: https://www.itead.cc/bare-pcb-pcb-process-capability-demonstrate-card.html

And logo and text on right lower part is used a Soldermask is visible very cleanly:

![im121222001_2](https://cloud.githubusercontent.com/assets/1379063/18225451/13fcb5de-71f2-11e6-8270-a9c7e8effabf.jpg)

Also using ENIG pops even more:
https://www.tindie.com/products/NsN/pcb-color-sample-set/

![im121222001_2](https://d3s5r33r268y59.cloudfront.net/1334/products/thumbs/collection.jpg.855x570_q85_pad_rcrop.jpg)

**Comment by m3us** [comment]
Displaying text on PCB using solder mask and ENIG coating would look nice.Especially if it is black color PCB.

![image](https://cloud.githubusercontent.com/assets/6883277/18315136/faffda88-7526-11e6-86bc-ae09717e45e5.png)

Since you did ENIG coating for latest batch maybe you could look into this for next one.

**Comment by m3us** [comment]
I just got KiCAD and I'm working on moving the items from silkscreen to solder mask layer.

**Comment by zigastegu** [comment]
It takes a simple find and replace in text editor and you are done ;) KiCad files are text based

**Comment by m3us** [comment]
Lol.You are right
![image](https://cloud.githubusercontent.com/assets/6883277/18418294/15151c1e-7854-11e6-90b7-6333e5ffe075.png)

Either way what do you think about the colour scheme?I have seen this in real life before and it looks nice

**Comment by zigastegu** [comment]
I think I will stay with blue and hasl for this batch. Black is black :) and wants to hide, but sure looks polished.

**Comment by m3us** [comment]
Okay :(
I suggested it because the aluminium enclosure is black.

**Comment by zigastegu** [comment]
Is blue, gold not your color of liking ? :)

**Comment by m3us** [comment]
Blue PCB with gold aluminum enclosure like what you have looks nice..
Blue PCB with black aluminum enclosure not so much,hence why I suggest black PCB for black enclosure.

**Comment by xmikos** [comment]
If I can weight in, I would also much more prefer black PCB :-) Most people will have black enclosure and black PCB looks better with it.

**Comment by zigastegu** [comment]
close this issue, Text stays on Silkscreen for now.
Panel colour is defined at production order
